apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pdf-knowledge
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.pdfSize }}
  storageClassName: {{ .Values.storage.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vector-store
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.vectorStoreSize }}
  storageClassName: {{ .Values.storage.storageClass }}
